openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
paths:
  /author:
    get:
      summary: Author
      responses:
        '200':
          description: Author of API
          content:
            application/json:
              schema:
                type: string
                example: 'Gaston Ciancio'
  /authenticate:
    post:
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Authentication token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /products:
    get:
      summary: List products
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: sbsfhnbsfhsrh546737gghghsewhsfhr
          description: Token for API request
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    post:
      summary: Create a product
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
          example: sbsfhnbsfhsrh546737gghghsewhsfhr
        description: Token for API request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '202':
          description: Product creation scheduled
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
